### ISSUE TITLE
 scala.MatchError: None (of class scala.None$) issue when using the latest version.

### ISSUE THREAD

**Issue by machaval** [hierynomus/scalariform-gradle-plugin#1]
Caused by: scala.MatchError: None (of class scala.None$)
        at scalariform.lexer.ScalaLexer.nextChar(ScalaLexer.scala:122)
        at scalariform.lexer.ScalaOnlyLexer$class.fetchScalaToken(ScalaOnlyLexer.scala:37)
        at scalariform.lexer.ScalaLexer.fetchScalaToken(ScalaLexer.scala:14)
        at scalariform.lexer.ScalaLexer.next(ScalaLexer.scala:192)
        at scalariform.lexer.WhitespaceAndCommentsGrouper.<init>(WhitespaceAndCommentsGrouper.scala:8)
        at scalariform.lexer.ScalaLexer$.tokenise(ScalaLexer.scala:263)
        at scalariform.formatter.SpecificFormatter$class.fullFormat(SpecificFormatter.scala:31)
        at scalariform.formatter.ScalaFormatter$$anon$1.fullFormat(ScalaFormatter.scala:476)
        at scalariform.formatter.ScalaFormatter$.formatAsEdits(ScalaFormatter.scala:485)
        at scalariform.formatter.ScalaFormatter$.format(ScalaFormatter.scala:469)
        at nl.javadude.gradle.plugins.scalariform.tasks.Scalariform$_format_closure1.doCall(Scalariform.groovy:44)
        at nl.javadude.gradle.plugins.scalariform.tasks.Scalariform.format(Scalariform.groovy:41)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 57 more

**Comment by hierynomus** [comment]
A bit more information would be welcome. What is the scalariform
configuration in `build.gradle`? Does it fail for all your
projects/sources, or just one? What is the `INFO` level logging of the
scalariform plugin (i.e. `gradle -i`)?

2016-06-27 16:33 GMT+02:00 Mariano de Achaval notifications@github.com:

**Comment by machaval** [comment]
I debug the issue and looks like the problem is that Scalariform creates a new instance of None instead of using the singleton instance. I created a pull request to fix this. If you can merge it and release a new version with the fix I will really appreciate. 
Regards,
Mariano A

**Comment by hierynomus** [comment]
Merged #2. This should be fixed now.

**Comment by hierynomus** [comment]
v1.1.2 is released with this fix.
